<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/8/11
 * Time: 19:08
 */


namespace app\common;


use think\Model;

class Person extends Model
{
    protected $pk = 'person_id';
    protected $json = ['person_name'];
    protected $field = ['person_id', 'person_name', 'person_sex', 'person_age', 'person_ct'];
//    protected $autoWriteTimestamp = 'timestamp';
//    protected $createTime = 'person_ct';
//    protected $updateTime = null;

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}